// Auto-generated by RusEFI Custom Firmware Studio for "Urutau English english"
// Board: urutau (ARCH_STM32F4)

#include "pch.h"
#include "board_overrides.h"

Gpio getCommsLedPin() {
	return Gpio::Unassigned;
}

Gpio getRunningLedPin() {
	return Gpio::Unassigned;
}

Gpio getWarningLedPin() {
	return Gpio::Unassigned;
}

static void customBoardDefaultConfiguration() {
	// === Reserve secondary UART pads (auto: prevents ADC/event_inputs hijack) ===
	engineConfiguration->binarySerialTxPin = Gpio::A2;
	engineConfiguration->binarySerialRxPin = Gpio::A3;
	engineConfiguration->uartConsoleSerialSpeed = 115200;
	efiSetPadMode("ts_uart_tx", Gpio::A2, PAL_MODE_ALTERNATE(7));
	efiSetPadMode("ts_uart_rx", Gpio::A3, PAL_MODE_ALTERNATE(7));
	// Pinos reservados pra UART (não serão atribuídos como ADC/saída): PA2, PA3, PC12, PC11, PC10, PD2

	// === SPI buses from pin table ===
	engineConfiguration->is_enabled_spi_3 = true;
	engineConfiguration->spi3mosiPin = Gpio::C12;
	engineConfiguration->spi3misoPin = Gpio::C11;
	engineConfiguration->spi3sckPin = Gpio::C10;
	engineConfiguration->spi3SckMode = PO_DEFAULT;
	engineConfiguration->spi3MosiMode = PO_DEFAULT;
	engineConfiguration->spi3MisoMode = PO_DEFAULT;
	engineConfiguration->sdCardSpiDevice = SPI_DEVICE_3;
	engineConfiguration->sdCardCsPin = Gpio::D2;
	engineConfiguration->sdCardCsPinMode = OM_DEFAULT;

	// === Injectors ===
	engineConfiguration->injectionPins[0] = Gpio::B12; // INJ1
	engineConfiguration->injectionPins[1] = Gpio::B13; // INJ2
	engineConfiguration->injectionPins[2] = Gpio::B14; // INJ3
	engineConfiguration->injectionPins[3] = Gpio::B15; // INJ4
	engineConfiguration->injectionPins[4] = Gpio::C6; // INJ5
	engineConfiguration->injectionPins[5] = Gpio::C7; // INJ6
	engineConfiguration->injectionPins[6] = Gpio::C8; // INJ7
	engineConfiguration->injectionPins[7] = Gpio::C9; // INJ8

	// === Ignition ===
	engineConfiguration->ignitionPins[0] = Gpio::A8; // IGN1
	engineConfiguration->ignitionPins[1] = Gpio::A9; // IGN2
	engineConfiguration->ignitionPins[2] = Gpio::A10; // IGN3
	engineConfiguration->ignitionPins[3] = Gpio::B6; // IGN4

	// === Analog inputs ===
	engineConfiguration->adcVcc = 3.3f;
	// GPS_RX on  (EFI_ADC_NONE) — assign as needed
	engineConfiguration->map.sensor.hwChannel = EFI_ADC_1;
	engineConfiguration->map.sensor.type = MT_MPX4250A;  // change in TS if different
	engineConfiguration->map.sensor.lowValue = 20;
	engineConfiguration->map.sensor.highValue = 250;
	engineConfiguration->clt.adcChannel = EFI_ADC_5;
	engineConfiguration->clt.config.bias_resistor = 2400;
	engineConfiguration->clt.config.tempC_1 = -10;
	engineConfiguration->clt.config.tempC_2 = 25;
	engineConfiguration->clt.config.tempC_3 = 80;
	engineConfiguration->clt.config.resistance_1 = 9397;
	engineConfiguration->clt.config.resistance_2 = 2500;
	engineConfiguration->clt.config.resistance_3 = 320;
	engineConfiguration->iat.adcChannel = EFI_ADC_4;
	engineConfiguration->iat.config.bias_resistor = 2400;
	engineConfiguration->iat.config.tempC_1 = -10;
	engineConfiguration->iat.config.tempC_2 = 25;
	engineConfiguration->iat.config.tempC_3 = 80;
	engineConfiguration->iat.config.resistance_1 = 9397;
	engineConfiguration->iat.config.resistance_2 = 2500;
	engineConfiguration->iat.config.resistance_3 = 320;
	engineConfiguration->vbattAdcChannel = EFI_ADC_7;
	engineConfiguration->afr.hwChannel = EFI_ADC_6;
	engineConfiguration->afr.v1 = 0.0f;
	engineConfiguration->afr.value1 = 7.35f;
	engineConfiguration->afr.v2 = 5.0f;
	engineConfiguration->afr.value2 = 22.39f;
	engineConfiguration->tps1_1AdcChannel = EFI_ADC_0;
	engineConfiguration->tpsMin = 100;   // ADC counts at closed throttle (~0.5V)
	engineConfiguration->tpsMax = 800;   // ADC counts at WOT (~4.0V)
	engineConfiguration->tpsErrorDetectionTooLow = -10;
	engineConfiguration->tpsErrorDetectionTooHigh = 110;
	// NONE on PC0 (EFI_ADC_10) — assign as needed
	// NONE on PC1 (EFI_ADC_11) — assign as needed

	// === Outputs / triggers ===
	engineConfiguration->triggerInputPins[1] = Gpio::Unassigned;
	engineConfiguration->camInputs[1] = Gpio::Unassigned;
	engineConfiguration->triggerInputPins[0] = Gpio::C3;
	engineConfiguration->camInputs[0] = Gpio::C4;
	engineConfiguration->fuelPumpPin = Gpio::B11;
	engineConfiguration->fanPin = Gpio::B9;
	engineConfiguration->idle.solenoidPin = Gpio::A15;
	engineConfiguration->malfunctionIndicatorPin = Gpio::E3;
	engineConfiguration->tachOutputPin = Gpio::B7;
	engineConfiguration->idle.stepperDirectionPin = Gpio::B0;
	engineConfiguration->useStepperIdle = true;
	engineConfiguration->idle.stepperStepPin = Gpio::B1;
	engineConfiguration->stepperEnablePin = Gpio::B10;
	// NONE on PB2
	// NONE on PC13
	// NONE on PB8
	// NONE on PB5
	// NONE on PC5
	// TS_RX on 
	// TS_TX on 

	// === Voltage dividers (global + VBAT) ===
	// Global analog divider ratio = 1.500 (Rt=10000, Rb=20000) — applied to ALL analog inputs except VBAT
	engineConfiguration->analogInputDividerCoefficient = 1.5000f;
	// VBAT divider ratio = 7.200 (Rt=6200, Rb=1000)
	engineConfiguration->vbattDividerCoeff = 7.2000f;

	// === NTC bias (informational) ===
	// CLT: bias=2400Ω @ 3.33V (curve via cltBins/cltValues)
	// IAT: bias=2400Ω @ 3.33V (curve via cltBins/cltValues)
}

// Mirrors fw-custom-example: registers the override via the function pointer.
void setup_custom_board_overrides() {
	custom_board_DefaultConfiguration = customBoardDefaultConfiguration;
}
