[WueAnalyze]

;						wueCurveName, afrTempCompensationCurve, lambdaTargetTableName, lambdaChannel, coolantTempChannel, egoCorrectionChannel, wueChannel, activeCondition
	wueAnalyzeMap = wueAnalyzer_warmup_curve, wueAfrTargetOffsetCurve, lambdaTableTbl, lambdaValue, coolant, running_coolantTemperatureCoefficient, egoCorrectionForVeAnalyze, { useLambdaOnInterface }
	wueAnalyzeMap = wueAnalyzer_warmup_curve, wueAfrTargetOffsetCurve, afrTableTbl, AFRValue, coolant, running_coolantTemperatureCoefficient, egoCorrectionForVeAnalyze, { !useLambdaOnInterface }
	lambdaTargetTables = lambdaTableTbl, afrTSCustom

	wuePercentOffset = 0 ; for working with 0 based enrichment set to 100
	option = disableLiveUpdates
	option = burnOnSend

;	filter = std_DeadLambda ; Auto build

	filter = decelFilterMap,"Enriquecimento Pós-Partida", engine,			&	, 4 ,		, false
	filter = accelFilterTp, "Enriquecimento por Acel. TPS"	, engine,			&	, 16,		, false
	filter = decelFilterTp, "Enriquecimento por Decel. TPS"	, engine,			&	, 32,		, false
	filter = accelFilterMap,"Enriquecimento MAP Acel."  , engine,			&	, 64,		, false
	filter = decelFilterMap,"Enriquecimento MAP Decel."  , engine,			&	, 128,		, false
	; this works, just another way to skin a cat
	;filter = decelFilter, "Bandeira de desaceleração" , tpsaccden,			>		, 0,		, false
	filter = overrunFilter, "Corte de combustível em desaceleração"	, pulseWidth1,  =		, 0,				, false
	filter = highThrottle, "Borboleta Alta"	, throttle,  >		, 15,			, true
	filter = lowRpm,		"RPM Baixo"	,		rpm,		<		, 300,		, false
	filter = std_Custom ; Standard Custom Expression Filter.
